### PR TITLE
[Spark] Run the uc tests against both spark 4.0 and spark 4.1

### PR DESCRIPTION
**Pull request by openinx**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

As our UC 0.4.0, will need to support both spark4.0 and spark4.1, then let's just make a temporary PR, to test out if there is any issue while work with spark 4.1. 

DON'T MERGE THIS PR, right now.   Just use this PR to test out the potential break, while use the spark 4.1.

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -19,11 +19,11 @@ val artifactNamePrefix = "unitycatalog"
 lazy val javacRelease11 = Seq("--release", "11")
 lazy val javacRelease17 = Seq("--release", "17")
 
-lazy val scala213 = "2.13.16"
```
Comment (openinx) [inline build.sbt:22]: The Problem: Every spark connector test failure in target/job-logs.txt is caused by the same error:

```
NoSuchMethodError: 'java.lang.String scala.util.hashing.MurmurHash3$.caseClassHash$default$2()'
```

Root Cause: Scala version mismatch between Spark 4.1.0 (compiled with Scala 2.13.17) and Unity Catalog (using Scala 2.13.16).
Scala 2.13.17 introduced a breaking change 1: MurmurHash3.productHash was deprecated and a new MurmurHash3.caseClassHash method was added with default parameters. Spark 4.1.0 was compiled with Scala 2.13.17 (via SPARK-53585), so its bytecode calls the new caseClassHash$default$2() accessor. When running with scala-library-2.13.16, that method doesn't exist.
The Fix: Updated build.sbt line 22:

```
// Before lazy val scala213 = "2.13.16"
// After  lazy val scala213 = "2.13.17"
```

This aligns Unity Catalog's Scala runtime library with what Spark 4.1.0 was compiled against, resolving the binary incompatibility.

**Comment by openinx** [comment]
All test passed, the remaining thing is the license check failure: https://github.com/unitycatalog/unitycatalog/actions/runs/21850779463/job/63056709335?pr=1345

```
build/sbt licenseCheck

[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.netty#netty-codec-native-quic;4.2.7.Final: java.net.URISyntaxException: Illegal character in path at index 113: [https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.${packaging.type}](https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.$%7Bpackaging.type%7D)
[error] 	at sbtlicensereport.license.LicenseReport$.$anonfun$resolve$1(LicenseReport.scala:233)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:267)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:212)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:72)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:82)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:82)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:203)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:266)
[error] 	at sbtlicensereport.license.LicenseReport$.resolve(LicenseReport.scala:221)
[error] 	at sbtlicensereport.license.LicenseReport$.makeReport(LicenseReport.scala:124)
[error] 	at sbtlicensereport.SbtLicenseReport$.$anonfun$projectSettings$2(SbtLicenseReport.scala:95)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.unitycatalog#unitycatalog-client;0.3.1: configuration not public in io.unitycatalog#unitycatalog-client;0.3.1: 'test'. It was required from io.unitycatalog#unitycatalog-cli;0.3.0-SNAPSHOT test
[error] 	at sbtlicensereport.license.LicenseReport$.$anonfun$resolve$1(LicenseReport.scala:233)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:267)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:212)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:72)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:82)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:82)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:203)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:266)
[error] 	at sbtlicensereport.license.LicenseReport$.resolve(LicenseReport.scala:221)
[error] 	at sbtlicensereport.license.LicenseReport$.makeReport(LicenseReport.scala:124)
[error] 	at sbtlicensereport.SbtLicenseReport$.$anonfun$projectSettings$2(SbtLicenseReport.scala:95)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (spark / updateLicenses) sbt.librarymanagement.ResolveException: unresolved dependency: io.netty#netty-codec-native-quic;4.2.7.Final: java.net.URISyntaxException: Illegal character in path at index 113: [https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.${packaging.type}](https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.$%7Bpackaging.type%7D)
[error] (cli / updateLicenses) sbt.librarymanagement.ResolveException: unresolved dependency: io.unitycatalog#unitycatalog-client;0.3.1: configuration not public in io.unitycatalog#unitycatalog-client;0.3.1: 'test'. It was required from io.unitycatalog#unitycatalog-cli;0.3.0-SNAPSHOT test
[error] Total time: 177 s (02:57), completed Feb 10, 2026, 4:11:25 AM
```

File: build.sbt (hunk 1 above)
Comment (openinx) [reply build.sbt:22]: Otherwise, it will throw this error.

```
[error] java.lang.NoSuchMethodError: 'java.lang.String scala.util.hashing.MurmurHash3$.caseClassHash$default$2()'
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$_hashCode$1(TreeNode.scala:226)
[error] 	at org.apache.spark.util.BestEffortLazyVal.apply(BestEffortLazyVal.scala:53)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.hashCode(TreeNode.scala:227)
[error] 	at java.base/java.util.Objects.hashCode(Objects.java:103)
[error] 	at org.apache.spark.sql.catalyst.expressions.Alias.$anonfun$hashCode$1(namedExpressions.scala:241)
[error] 	at org.apache.spark.sql.catalyst.expressions.Alias.$anonfun$hashCode$1$adapted(namedExpressions.scala:241)
[error] 	at scala.collection.immutable.List.map(List.scala:251)
[error] 	at scala.collection.immutable.List.map(List.scala:79)
[error] 	at org.apache.spark.sql.catalyst.expressions.Alias.hashCode(namedExpressions.scala:241)
[error] 	at scala.runtime.Statics.anyHash(Statics.java:127)
[error] 	at scala.collection.immutable.HashSetBuilder.addOne(HashSet.scala:2073)
[error] 	at scala.collection.immutable.HashSetBuilder.addOne(HashSet.scala:1955)
[error] 	at scala.collection.immutable.Set$Set4.buildTo(Set.scala:352)
[error] 	at scala.collection.immutable.SetBuilderImpl.addOne(Set.scala:392)
[error] 	at scala.collection.immutable.SetBuilderImpl.addOne(Set.scala:362)
[error] 	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
[error] 	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
[error] 	at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:405)
[error] 	at scala.collection.immutable.Set$.from(Set.scala:362)
[error] 	at scala.collection.IterableOnceOps.toSet(IterableOnce.scala:1469)
[error] 	at scala.collection.IterableOnceOps.toSet$(IterableOnce.scala:1469)
[error] 	at scala.collection.AbstractIterable.toSet(Iterable.scala:935)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$_containsChild$1(TreeNode.scala:219)
[error] 	at org.apache.spark.util.BestEffortLazyVal.apply(BestEffortLazyVal.scala:53)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.containsChild(TreeNode.scala:220)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:728)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1264)
[error] 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1263)
[error] 	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:587)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:496)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:729)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1264)
[error] 	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1263)
[error] 	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:587)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:496)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsDownWithPruning$1(QueryPlan.scala:216)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:257)
[error] 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:107)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:257)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:269)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:275)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:275)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$5(QueryPlan.scala:280)
[error] 	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:333)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:280)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsDownWithPruning(QueryPlan.scala:216)
[error] 	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsWithPruning(QueryPlan.scala:187)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveExpressionsDownWithPruning$1.applyOrElse(AnalysisHelper.scala:307)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveExpressionsDownWithPruning$1.applyOrElse(AnalysisHelper.scala:306)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:200)
[error] 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:107)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:200)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:416)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:198)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:194)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:37)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:100)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:97)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:37)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsDownWithPruning(AnalysisHelper.scala:306)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsDownWithPruning$(AnalysisHelper.scala:303)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveExpressionsDownWithPruning(LogicalPlan.scala:37)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning(AnalysisHelper.scala:278)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning$(AnalysisHelper.scala:276)
[error] 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveExpressionsWithPruning(LogicalPlan.scala:37)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$.apply(Analyzer.scala:2161)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$.apply(Analyzer.scala:2157)
[error] 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:248)
[error] 	at scala.collection.immutable.ArraySeq.foldLeft(ArraySeq.scala:222)
[error] 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:245)
[error] 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:237)
[error] 	at scala.collection.immutable.List.foreach(List.scala:334)
[error] 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:237)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:343)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:339)
[error] 	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:224)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:339)
[error] 	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:289)
[error] 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfu
```

File: build.sbt [hunk 2]
```diff
@@ -553,6 +553,7 @@ lazy val serverShaded = (project in file("server-shaded"))
     assembly / assemblyShadeRules := Seq(
       ShadeRule.rename("com.fasterxml.**" -> "shaded.@0").inAll,
       ShadeRule.rename("org.antlr.**" -> "shaded.@0").inAll,
+      ShadeRule.rename("io.netty.**" -> "shaded.@0").inAll,
```
Comment (openinx) [inline build.sbt:556]: When the Spark connector tests run, two components are loaded in the same JVM:                                                                                                        
                                                                                                                                                                                        
  1. Spark 4.1 — bundles Netty 4.2 (which changed SingleThreadEventLoop's constructor signature)                                                                                        
  2. serverShaded test jar — embeds the UC server, which depends on `"io.netty" % "netty-all" % "4.1.111.Final"`
                                                                                                                                                                                        
  Without shading, both Netty versions land on the classpath. The JVM loads one `io.netty.channel.SingleThreadEventLoop` class — whichever comes first — and when Spark 4.1 tries to call
  the Netty 4.2 constructor, it finds the Netty 4.1 class instead and throws NoSuchMethodError.

  By relocating `io.netty.** → shaded.io.netty.**` inside serverShaded, the UC server's Netty gets a different package name entirely. The two Netty versions no longer compete — Spark
  uses io.netty.* (4.2) and the server uses shaded.io.netty.* (4.1), with zero collision.

Comment (openinx) [reply build.sbt:556]: This fix actually, also helps us to fix this problem that we encountered in the delta-io's test.
https://github.com/delta-io/delta/issues/5624#issuecomment-3673383736

File: build.sbt [hunk 3]
```diff
@@ -647,6 +648,8 @@ lazy val spark = (project in file("connectors/spark"))
       case DepModuleInfo("org.glassfish", "javax.json", _) => true
       case DepModuleInfo("org.glassfish.hk2.external", "jakarta.inject", _) => true
       case DepModuleInfo("org.antlr", "ST4", _) => true
+      // netty-codec-native-quic uses ${packaging.type} in its POM which Ivy cannot resolve
+      case DepModuleInfo("io.netty", "netty-codec-native-quic", _) => true
```
Comment (openinx) [inline build.sbt]: **Root cause:** netty-codec-native-quic (a new Netty 4.2.x native artifact pulled in transitively by Spark 4.1.0) has ${packaging.type} as an unresolved Maven property in its POM. The  sbt-license-report plugin uses Ivy for resolution, and Ivy doesn't substitute that property — so the URL it constructs is literally .../netty-codec-native-quic-4.2.7.Final.${packaging.type}, which is invalid.                                                                                                          
                                                                                                                                                                                        
  Fix: Exclude io.netty:netty-codec-native-quic from the spark project's licenseDepExclusions. The artifact is Apache 2.0 licensed (like all of Netty), so skipping the automated check is safe.

Comment (openinx) [reply build.sbt]: The failure is here: 

```
Using /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.18-8/x64 as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.18)
[info] loading settings for project unitycatalog-build from plugins.sbt ...
[info] loading project definition from /home/runner/work/unitycatalog/unitycatalog/project
[info] loading settings for project root from build.sbt,version.sbt ...
[info] resolving key references (12806 settings) ...
[info] set current project to unitycatalog (in build file:/home/runner/work/unitycatalog/unitycatalog/)
[info] org.slf4j#slf4j-log4j12;2.0.13 is relocated to org.slf4j#slf4j-reload4j;2.0.13. Please update your dependencies.
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[info] Found only allowed licenses among the dependencies!
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.netty#netty-codec-native-quic;4.2.7.Final: java.net.URISyntaxException: Illegal character in path at index 113: [https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.${packaging.type}](https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.$%7Bpackaging.type%7D)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Found only allowed licenses among the dependencies!
[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.netty#netty-codec-native-quic;4.2.7.Final: java.net.URISyntaxException: Illegal character in path at index 113: [https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.${packaging.type}](https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.$%7Bpackaging.type%7D)
[error] 	at sbtlicensereport.license.LicenseReport$.$anonfun$resolve$1(LicenseReport.scala:233)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:267)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:212)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:72)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:82)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:82)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:203)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:266)
[error] 	at sbtlicensereport.license.LicenseReport$.resolve(LicenseReport.scala:221)
[error] 	at sbtlicensereport.license.LicenseReport$.makeReport(LicenseReport.scala:124)
[error] 	at sbtlicensereport.SbtLicenseReport$.$anonfun$projectSettings$2(SbtLicenseReport.scala:95)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[error] (spark / updateLicenses) sbt.librarymanagement.ResolveException: unresolved dependency: io.netty#netty-codec-native-quic;4.2.7.Final: java.net.URISyntaxException: Illegal character in path at index 113: [https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.${packaging.type}](https://repo1.maven.org/maven2/io/netty/netty-codec-native-quic/4.2.7.Final/netty-codec-native-quic-4.2.7.Final.$%7Bpackaging.type%7D)
[error] Total time: 183 s (03:03), completed Mar 2, 2026, 11:23:40 PM
```

**Review by tdas — APPROVED** [review]
