### ISSUE TITLE
Unable to run uc cli in docker container

### ISSUE THREAD

**Issue by fixl** [unitycatalog/unitycatalog#1381]
**Describe the bug**

Running `uc` inside docker container throws and exception.

**To Reproduce**

```
$ docker run --rm -it unitycatalog/unitycatalog:v0.4.0 bin/uc --help
Error: Unable to initialize main class io.unitycatalog.cli.UnityCatalogCli
Caused by: java.lang.NoClassDefFoundError: io/unitycatalog/client/ApiException
```

**Expected behavior**

Show help menu

**System [please complete the following information]:**

- OS: Mac OS Tahoe
- Docker: colima

**Additional context**

This is still the same issue as #1283

**Comment by abij** [comment]
I can confirm it's working for the new version (`unitycatalog/unitycatalog:main`), resolved in #1357, while waiting for the 0.5.0 release...
you _can_  make it work with v0.4.0, adding the missing classes:

```shell
# Using the local project build artefacts
# Start container with mounting the missing client classes.
docker run --name uctest --rm -v $(PWD)/clients/java/target/classes:/home/unitycatalog/clients/java/target/classes unitycatalog/unitycatalog:v0.4.0 bin/uc --help

Usage: bin/uc <entity> <operation> [options]
Entities: schema, model_version, metastore, auth, catalog, permission, volume, credential, function, registered_model, user, table, external_location

By default, the client will connect to UC running locally at http://localhost:8080

To connect to specific UC server, use --server https://<host>:<port>

Currently, auth using bearer token is supported. Please specify the token via --auth_token <PAT Token>

For detailed help on entity specific operations, use bin/uc <entity> --help
```
