### ISSUE TITLE
Following getting started with docker results in Error: Unable to initialize main class io.unitycatalog.cli.UnityCatalogCli

### ISSUE THREAD

**Issue by saxomoose** [unitycatalog/unitycatalog#1283]
**Describe the bug**

Following getting started guide for docker: https://docs.unitycatalog.io/docker_compose/
Using images with `:latest` tag.
UI runs fine.
Trying to use CLI results in:
```text
Error: Unable to initialize main class io.unitycatalog.cli.UnityCatalogCli
Caused by: java.lang.NoClassDefFoundError: io/unitycatalog/client/ApiException
```

**To Reproduce**

Getting started guide for docker

**System [please complete the following information]:**

-  OS: Ubuntu running on WSL
-  Docker: CLI

**Comment by saxomoose** [comment]
Fails on `latest` and `v0.3.1` tags.

**Comment by light-lee-2016** [comment]
I also encountered the same error, is there any temporary solution to fix it?

**Comment by jonsnowseven** [comment]
I have the same problem. Does this mean that the latest Unity Catalog docker image is unusable?

**Comment by jonsnowseven** [comment]
I confirm that it works with `v0.3.0` tag

**Comment by ThierryGirod** [comment]
Same here also with the newly released `v0.4.0`

**Comment by sassai** [comment]
Same here. I'm trying to create a user via the CLI inside of the Docker container.  Is there any temporary solution to fix it?

**Comment by ThierryGirod** [comment]
@tdas  @roeap Problem seems fixed but the image on dockerhub still shows the error. Could you also redeploy on dockerhub ?

**Comment by tdas** [comment]
@roeap please do your magic in docker
