### ISSUE TITLE
Compile error when upgrade the delta version from 4.0.0 to the master branch of OSS-delta.

### ISSUE THREAD

**Issue by openinx** [unitycatalog/unitycatalog#1219]
I tried to use the lastest version of the OSS-Delta to build the OSS-UC, but I failed. 

The error message is here:

```bash
[info]   Use -proc:none to disable annotation processing.
[error] /Users/zheng.hu/repo/unitycatalog/examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelReadUtils.java:112:1: method getPhysicalDataReadSchema in class io.delta.kernel.internal.data.ScanStateRow cannot be applied to given types;
[error]   required: io.delta.kernel.data.Row
[error]   found:    io.delta.kernel.engine.Engine,io.delta.kernel.data.Row
[error]   reason: actual and formal argument lists differ in length
[error] ScanStateRow.getPhysicalDataReadSchema
[error] /Users/zheng.hu/repo/unitycatalog/examples/cli/src/main/java/io/unitycatalog/cli/delta/DeltaKernelReadUtils.java:123:1: incompatible types: io.delta.kernel.utils.CloseableIterator<io.delta.kernel.engine.FileReadResult> cannot be converted to io.delta.kernel.utils.CloseableIterator<io.delta.kernel.data.ColumnarBatch>
[error] engine
[error]                     .getParquetHandler()
[error]                     .readParquetFiles(
[error]                         singletonCloseableIterator(fileStatus),
[error]                         physicalReadSchema,
[error]                         Optional.empty())
Generated classpath file '/Users/zheng.hu/repo/unitycatalog/server/target/classpath'
[warn] 10 deprecations (since 2.13.0)
[warn] 1 deprecation (since 2.13.3)
[warn] 11 deprecations in total; re-run with -deprecation for details
[warn] three warnings found
[info] Annotation processing is enabled because one or more processors were found
[info]   on the class path. A future release of javac may disable annotation processing
[info]   unless at least one processor is specified by name (-processor), or a search
[info]   path is specified (--processor-path, --processor-module-path), or annotation
[info]   processing is enabled explicitly (-proc:only, -proc:full).
[info]   Use -Xlint:-options to suppress this message.
[info]   Use -proc:none to disable annotation processing.
Generated classpath file '/Users/zheng.hu/repo/unitycatalog/connectors/spark/target/scala-2.13/classpath'
[error] (cli / Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 7 s, completed Nov 18, 2025, 9:05:37 PM
```

**Comment by openinx** [comment]
I just changed the version of OSS-Delta from `3.4.0-SNAPSHOT` to `4.0.1-SNAPSHOT`. (Following are the OSS-Delta changes)

```diff
diff --git a/version.sbt b/version.sbt
index 074f34884..ff946cb1c 100644
--- a/version.sbt
+++ b/version.sbt
@@ -1 +1 @@
-ThisBuild / version := "3.4.0-SNAPSHOT"
+ThisBuild / version := "4.0.1-SNAPSHOT"
```

And then I upgrade the delta version of OSS-UC from `4.0.0` to `4.0.1-SNAPSHOT`.  (Following are OSS-UC changes )


```diff
diff --git a/build.sbt b/build.sbt
index 18a78af..30d18c2 100644
--- a/build.sbt
+++ b/build.sbt
@@ -21,7 +21,7 @@ lazy val javacRelease17 = Seq("--release", "17")
 
 lazy val scala213 = "2.13.16"
 
-lazy val deltaVersion = "4.0.0"
+lazy val deltaVersion = "4.0.1-SNAPSHOT"
 lazy val sparkVersion = "4.0.0"
 lazy val hadoopVersion = "3.4.0"
```

When I build the OSS-UC,  it just throw the above message.

**Comment by openinx** [comment]
After I applied this changes to OSS-UC, everything is okay. So the only thing that I need to change is the `example` module. 

```diff
diff --git a/build.sbt b/build.sbt
index 18a78af..6865d29 100644
--- a/build.sbt
+++ b/build.sbt
@@ -21,7 +21,7 @@ lazy val javacRelease17 = Seq("--release", "17")
 
 lazy val scala213 = "2.13.16"
 
-lazy val deltaVersion = "4.0.0"
+lazy val deltaVersion = "4.0.1-SNAPSHOT"
 lazy val sparkVersion = "4.0.0"
 lazy val hadoopVersion = "3.4.0"
 
@@ -661,7 +661,7 @@ lazy val integrationTests = (project in file("integration-tests"))
   )
 
 lazy val root = (project in file("."))
-  .aggregate(serverModels, client, pythonClient, server, cli, spark, controlApi, controlModels, apiDocs)
+  .aggregate(serverModels, client, pythonClient, server, spark, controlApi, controlModels, apiDocs)
   .settings(
     name := s"$artifactNamePrefix",
     createTarballSettings(),
```
